
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/people?serverTimezone=UTC
    username: root
    password: why594309020
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  jpa:
    show-sql: true
    thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
logging:
  level:
    com:
      example: debug

